spring.application.name=skyform


# =====================================================================
# MySQL Connection (Local - Docker Container)
# =====================================================================
#spring.datasource.url=${MYSQL_CONNECTION_STRING}
#spring.datasource.username=${MYSQL_DATABASE}
#spring.datasource.password=${MYSQL_ROOT_PASSWORD}

# =====================================================================
# MySQL Connection (GCP - Cloud SQL)
# =====================================================================
spring.datasource.url=${GCP_MYSQL_CONNECTION_STRING}
spring.datasource.username=${GCP_MYSQL_USERNAME}
spring.datasource.password=${GCP_MYSQL_ROOT_PASSWORD}

## =====================================================================
## MySQL Connection (Aiven Managed Instance)
## =====================================================================
#spring.datasource.url=${AIVEV_DATASOURCE_URL}
#spring.datasource.username=${AIVEN_DATASOURCE_USERNAME}
#spring.datasource.password=${AIVEN_DATASOURCE_PASSWORD}

# Run the sql schema automatically
spring.sql.init.mode=always



# JPA / Hibernate Properties
#spring.jpa.hibernate.ddl-auto=validate
#Change validate to update while developing so Hibernate creates/updates tables automatically:
propertiesspring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.show_sql=true


spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Enable XML formatting explicitly if needed
spring.mvc.contentnegotiation.favor-parameter=false
spring.mvc.contentnegotiation.ignore-accept-header=false

server.port=8080

logging.level.org.springframework.web=DEBUG

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=20MB
app.upload.dir=./uploads/certificates


